### PR TITLE
Pull request for code review

### PR DESCRIPTION
**Pull request by luis-novoa**

### CODE REVIEW

**Comment by luis-novoa** [comment]
Hi,

we were able to activate the stickler, but it is showing errors that are not from our code. We downloaded the model webpage so we could have always the same news as reference to what insert in the page. Also, we're using "genericons", a set of icons, and its CSS file is filled with unfixable errors. How should we proceed? 

Luis Novoa

**Comment by shshamim63** [comment]
### Changes Required!
___
Hi @luis-novoa  & @ferdelvalle  :wave:
Well there is a way to fix it. All you have to do is ignore those files in stylelint.config.js.
Please take a look at this [link](https://stackoverflow.com/questions/56414776/stylelint-ignore-specific-folders-and-files)
I hope it will solve the issue. :smiley:.  
#### Please Fix the mentioned issues and send a final review request.
___
##### Happy Coding
##### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Comment by luis-novoa** [comment]
I managed to solve the issue using this configuration: https://stickler-ci.com/docs.

**Review by Redvanisation — APPROVED** [review]
### Hello team 🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
