### PR TITLE
Pull request for group review

### PR DESCRIPTION
**Pull request by luis-novoa**

### CODE REVIEW

**Comment by ebukaume** [comment]
### Changes Required :stop_sign: 

Hi @luis-novoa  and @ferdelvalle :wave: 

You guys have done exceptionally well. You really paid close attention to the requirements and the behaviours of the page to be cloned. Please keep it up.

Let's just attend to these few issues and we'd be good to go.

- [x] Make the TNW logo appear only at the leftmost part of the screen at the medium breakpoint. ( _Refer to this images below_ )

**Theirs**
tnw-medium

**Yours**
tnw-clone-medium

- [x] Move the `<footer>` tag out of the main block. ( That way, you have `<header><main><footer>` )

- [x] Properly set up linter for this project. ( _Refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) and make sure you set it up correctly_ )

Also, refer to [this guide](https://github.com/RomuloOliveira/commit-messages-guide) for guidelines on the importance of commit messages and how to get better at them. It would be nice if you would make start applying them from your next commits.

**Kindly submit another code review request after making those changes.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by ferdelvalle** [comment]
> ### Changes Required 🛑
> Hi @luis-novoa and @ferdelvalle 👋
> 
> You guys have done exceptionally well. You really paid close attention to the requirements and the behaviours of the page to be cloned. Please keep it up.
> 
> Let's just attend to these few issues and we'd be good to go.
> 
> * [x]  Make the TNW logo appear only at the leftmost part of the screen at the medium breakpoint. ( _Refer to this images below_ )
> 
> **Theirs**
> tnw-medium
> 
> **Yours**
> tnw-clone-medium
> 
> * [x]  Move the `<footer>` tag out of the main block. ( That way, you have `<header><main><footer>` )
> * [x]  Properly set up linter for this project. ( _Refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) and make sure you set it up correctly_ )
> 
> Also, refer to [this guide](https://github.com/RomuloOliveira/commit-messages-guide) for guidelines on the importance of commit messages and how to get better at them. It would be nice if you would make start applying them from your next commits.
> 
> **Kindly submit another code review request after making those changes.**
> 
> Happy Coding ✌️
> **Ebuka Umeokonkwo**
> [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)
Excellent Review, thank you so much for your effort

**Comment by suretrust** [comment]
**Great job thus far :raised_hands:  @luis-novoa and @ferdelvalle,**

Just one more thing to go, kindly setup linter for this project. Your linter display should be similar to the image below when properly set. You can check [here](https://github.com/microverseinc/linters-config/tree/master/css) to know how to do that.

linter2

**Note**: Kindly use GitHub flow for subsequent HTML projects.

**Please submit for another review once this has been done. Good luck guys! :tada:**

**Comment by shshamim63** [comment]
## Changes Required!
Hi, @luis-novoa & @ferdelvalle :wave: 
Awesome job on the project. Everything looks perfect except the linter check that was mentioned by @suretrust . 
Now the question what is the problem with the linter?
well if you click on check
check
you will see this :point_down: 
linterconfig
Which indicates two things,
___
1. You did not install stickler-ci on your repo please follow this [link](https://github.com/apps/stickler-ci).click on **configure** and after that select  **all repositories**
2. You forgot to enable stickler in your repository. To enable it go to this [link](https://stickler-ci.com/).
___
Well it is a simple task, but have to ensure that, linter is functional :slightly_smiling_face: 
#### Please configure your stickler and send a final code review.
## Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Pull request closed without merging**
